name: Github CI

#on: [pull_request]
on:
  # Configura servidor de CI para executar o pipeline de tarefas (jobs) quando 
  # um push ou pull request for realizado tendo como alvo a branch main
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
#        python-version: ["3.6", "3.7", "3.8", "3.9", "3.10"]
#    defaults:
#      run:
#        shell: bash
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2 # Faz o checkout do código recebido

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1 # Configura o Java 1.8
        with:
          java-version: 1.8

      - name: Build
        run: mvn package '-Dmaven.test.skip=true' # Compila o código fonte

      - name: Unit Test
        run: mvn test # Executada os testes de unidade
